import  Link  from 'next/link';
import styles from "./page.module.css";
import Image from 'next/image';
export const metadata = {
  title: 'HEXASHOP-products',
  description: 'Generated by create next app',
}
async function getData() {
  const res = await fetch('https://dummyjson.com/products')
  if (!res.ok) {
    throw new Error('Failed to fetch data')
  }
 
  return res.json()
}
export default async function Blog() {

  const data = await getData()
const products=data.products
  console.log(products);
    return (  
 <div className={styles.maincontainer}>
 {
  products.map(product=>
    <Link href={`/blog/${product.id}`} className={styles.post} key={product.id}>
      <div className={styles.imagecontainer}>
        <Image className={styles.image}
        src={product.thumbnail}
  fill
        alt='post'
        />   
     </div>
        <div className={styles.content}>
        <h1 className={styles.title}>{product.title}  </h1>
        <p className={styles.desc}>{product.description}</p>
      </div> 
    </Link>  )
 }       
      </div> 
      )
  }