import Navbar from '@/components/Navbar/navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'
import Footer from '@/components/Footer/footer'
import { ThemeProvider } from '@/context/ThemeContext'

const inter = Montserrat({
   subsets: ['latin']  ,
   weight:['400','700','900']})


export const metadata = {
  title: 'HEXASHOP-HOME',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
 <ThemeProvider>
      <div className='container'>
       <Navbar/>
      {children}
      <Footer/>
      </div> 
 </ThemeProvider>

 </body>
    </html>
  )
}
